
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-chatbot.fullname" . }}-ui
  labels:
    {{- include "ai-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{ include "ai-chatbot.name" . }}-ui

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-chatbot.fullname" . }}-server
  labels:
    {{- include "ai-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverService.type }}
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ include "ai-chatbot.name" . }}-server